### ISSUE TITLE
Roadmap to first stable release?

### ISSUE THREAD

**Issue by nferhat** [nferhat/fht-compositor#2]
There is a lot, and I mean A LOT of work to do in order to get things to be stable and bearable. This list is NOT definitive, and its growing the more I use the compositor myself on my machine, which has been the case for the past 3 months as of writing this.

- Global stuff that affects everything
  - [x] #3 
  - [x] #4
  - [x] #49 

- Layout/workspace logic
  - [x] #10
  - [x] #9
  - [ ] #15 
  - [x] Re-implement fullscreen windows

- Animations:
  - [x] Window opening/closing 375d96796a4fe70ca7befa9d7bbefee6d53725d8
  - [x] #8
  - [ ] Sending windows to workspaces 
 
- Protocol support
  - [x] #6 
  - [x] #7 
  - [x] #11
  - [x] wlr-output-management

- Other miscellaneous bug fixing
  - [x] Egui decides to sometimes NOT show up b8bbce6bb86e5cfd76db2d12378ba68a50955e98
  - [x] Support `overlay_cursor` for `wlr-screencopy` 
  - [x] ~~Figure out why OBS decides to crash with dmabuf screencopy?~~ wlrobs bug, not compositor implementation

**Comment by nferhat** [comment]
While yes 25.03 has been released, more will come in future updates

**Comment by nferhat** [comment]
Closing as this isnt relevant anymore
